name: Run UI-INDEX Bot Every Hour

on:
  schedule:
    - cron: "0 * * * *"  # اجرای هر 1 ساعت
  workflow_dispatch:      # قابلیت اجرای دستی از GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests python-dotenv

      - name: Run UI-index.py
        env:
          CMC_API_KEY: ${{ secrets.CMC_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python UI-index.py
